### ISSUE TITLE
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, pos 1

### ISSUE THREAD

**Issue by karanatree** [hengyunabc/zabbix-api#14]
Error coming at

Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, pos 1
    at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1248)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1158)
    at com.alibaba.fastjson.JSON.parse(JSON.java:141)
    at com.alibaba.fastjson.JSON.parse(JSON.java:125)
    at com.alibaba.fastjson.JSON.parse(JSON.java:112)
    at zabbixjavaapi.call(zabbixjavaapi.java:116)
    at zabbixjavaapi.apiVersion(zabbixjavaapi.java:93)
    at main.main(main.java:25)

Code

public JSONObject call(request request)
    {

```
    if(request.getAuthentication()==null)
    {
        request.setAuthentication(auth);
    }

    try 
    {
        HttpUriRequest httpRequest = org.apache.http.client.methods.RequestBuilder
                .post().setUri(uri)
                .addHeader("Content-Type", "application/json")
                .setEntity(new StringEntity(JSON.toJSONString(request)))
                .build();
        CloseableHttpResponse response = httpClient.execute(httpRequest);
        HttpEntity entity = response.getEntity();
        byte[] data = EntityUtils.toByteArray(entity);
        return (JSONObject) JSON.parse(data);
    } 
    catch (IOException e) 
    {
        throw new RuntimeException("DefaultZabbixApi call exception!", e);
    }




}
```

Could you help me out regarding this?

**Comment by hengyunabc** [comment]
Try to print the response string.

```java
System.out.println(new String(data));
```
