### ISSUE TITLE
Versions of the libraries

### ISSUE THREAD

**Issue by georgesouzafarias** [hengyunabc/zabbix-api#7]
Hi, I'm trying to use the Zabbix-api but I'm having some problem.

I think that the problem is the versions of the libraries, especially  the org.log4j.

So, Could you tell me which version I should use?

Thank you.

Follow the console error:

Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:140)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:119)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:328)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:280)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:301)
	at br.jus.tjrr.zabbixAPI.DefaultZabbixApi.<init>(DefaultZabbixApi.java:22)
	at br.jus.tjrr.javaclasses.ConexaoZabbixTeste.main(ConexaoZabbixTeste.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:140)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:119)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:328)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:280)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:301)
	at br.jus.tjrr.zabbixAPI.DefaultZabbixApi.<init>(DefaultZabbixApi.java:22)
	at br.jus.tjrr.javaclasses.ConexaoZabbixTeste.main(ConexaoZabbixTeste.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by hengyunabc** [comment]
You can try to add these into your pom.xml:
```xml
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>log4j-over-slf4j</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
```

In zabbix-api/pom.xml, I set their scope "test".

**Comment by georgesouzafarias** [comment]
Thank you, it Worked.
